export default function () {
	const entitlements = {
		free: {
			name: 'Free',
			ticket_types: ['asap', 'scheduled', 'sales_inquiry', 'billing', 'abuse'],
			ticket_count: 0,
			concurrent_ticket_count: 0,
			execution_count: 100000,
			user_count: 3,
			workflow_count: 15,
			workflow_runs: 1000,
			document_count: 0,
			document_size: 0,
		},
		basic: {
			name: 'Basic',
			ticket_count: 5,
			ticket_types: [
				'asap',
				'scheduled',
				'sales_inquiry',
				'billing',
				'abuse',
				'bug',
			],
			concurrent_ticket_count: 0,
			execution_count: 100000,
			user_count: 5,
			workflow_count: 15,
			workflow_runs: 500,
			document_count: 0,
			document_size: 0,
		},
		growth: {
			name: 'Growth',
			ticket_count: 10,
			ticket_types: [
				'asap',
				'scheduled',
				'sales_inquiry',
				'billing',
				'abuse',
				'bug',
				'new',
			],
			concurrent_ticket_count: 0,
			execution_count: 100000,
			user_count: 10,
			workflow_count: 25,
			workflow_runs: 5000,
			document_count: 0,
			document_size: 0,
		},
		enterprise: {
			name: 'Enterprise',
			ticket_count: 20,
			ticket_types: [
				'asap',
				'scheduled',
				'sales_inquiry',
				'billing',
				'abuse',
				'bug',
				'new',
				'performance_issues',
			],
			concurrent_ticket_count: 5,
			execution_count: 100000,
			user_count: 20,
			workflow_count: 200,
			workflow_runs: 5000,
			document_count: 500,
			document_size: 50000,
		},
	};
	return entitlements;
}
